[package]
name = "http-get"
version = "0.1.0"
authors = ["Muhammad Syakir bin Mohd Haris <syakirharis25@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.8.3"
